const CONFIG={TRADING_DAYS:252,GARCH_OMEGA:1e-6,GARCH_ALPHA:.08,GARCH_BETA:.9,KALMAN_PROCESS_VAR:1e-5,KALMAN_MEASUREMENT_VAR:1e-3};
const SCENARIOS={tech:{title:'Tech Leaders',assets:[['NVDA',1.15, .0022],['MSFT',.92,.0013],['AAPL',1.03,.0015]]},balanced:{title:'Balanced Portfolio',assets:[['SPY',1,.001],['TLT',-.12,.0011],['GLD',.08,.0014]]},volatile:{title:'High Beta Basket',assets:[['TSLA',1.55,.003],['AMD',1.34,.0027],['COIN',1.8,.0038]]}};
const $=id=>document.getElementById(id);let currentReport=null;
function seeded(seed){return()=>{seed=(seed*1664525+1013904223)%4294967296;return seed/4294967296}};
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function std(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function logReturns(prices){if(prices.some(x=>x<=0))throw Error('Prices must be strictly positive.');return prices.slice(1).map((x,i)=>Math.log(x/prices[i]))}
function annualizedVolatility(r){return std(r)*Math.sqrt(CONFIG.TRADING_DAYS)}
function maxDrawdown(prices){let peak=-Infinity,best=0;for(const p of prices){peak=Math.max(peak,p);best=Math.min(best,p/peak-1)}return best}
function beta(asset,market){if(asset.length<2)throw Error('At least two observations are required.');const am=mean(asset),mm=mean(market);const v=market.reduce((s,x)=>s+(x-mm)**2,0)/(market.length-1);if(v===0)throw Error('Market return variance cannot be zero.');return asset.reduce((s,x,i)=>s+(x-am)*(market[i]-mm),0)/(market.length-1)/v}
function garch(r){if(!r.length)throw Error('Returns cannot be empty.');let v=r.length>1?std(r)**2:CONFIG.GARCH_OMEGA/(1-CONFIG.GARCH_ALPHA-CONFIG.GARCH_BETA),out=[v];for(let i=1;i<r.length;i++)out.push(CONFIG.GARCH_OMEGA+CONFIG.GARCH_ALPHA*r[i-1]**2+CONFIG.GARCH_BETA*out[i-1]);return out}
function kalman(asset,market){let b=1,c=1,out=[];for(let i=0;i<asset.length;i++){c+=CONFIG.KALMAN_PROCESS_VAR;const innovation=asset[i]-market[i]*b,iv=market[i]**2*c+CONFIG.KALMAN_MEASUREMENT_VAR,k=c*market[i]/iv;b+=k*innovation;c=(1-k*market[i])*c;out.push(b)}return out}
function makeSeries(days,scenario,marketName){const random=seeded(scenario==='tech'?4381:scenario==='balanced'?9281:18501);const s=SCENARIOS[scenario],marketBeta=marketName==='QQQ'?1.1:1;const market=[100],assets=s.assets.map(([name,b,noise])=>({name,b,noise,prices:[100]}));for(let i=1;i<days;i++){const regime=Math.sin(i/13)*.0006+(random()-.5)*.0025;market.push(market[i-1]*Math.exp(regime));assets.forEach(a=>{const shock=regime*a.b*marketBeta+(random()-.5)*a.noise;a.prices.push(a.prices[i-1]*Math.exp(shock))})}return{market,assets,source:'Synthetic market data'} }
function analyze(series){const marketR=logReturns(series.market);const assets=series.assets.map(a=>{const r=logReturns(a.prices);const g=garch(r);return{...a,returns:r,vol:annualizedVolatility(r),dd:maxDrawdown(a.prices),beta:beta(r,marketR),garch:g,kalman:kalman(r,marketR),last:a.prices.at(-1)}});return{...series,assets,marketR,marketVol:annualizedVolatility(marketR),marketGarch:garch(marketR)}}
function nicePct(x){return `${(x*100).toFixed(2)}%`}function niceNum(x){return x.toFixed(2)}
function renderMetrics(r){const avgVol=mean(r.assets.map(a=>a.vol)),worst=Math.min(...r.assets.map(a=>a.dd)),avgBeta=mean(r.assets.map(a=>a.beta));$('metric-grid').innerHTML=[['PORTFOLIO VOLATILITY',nicePct(avgVol),'Annualized · equal weighted','metric-accent'],['WORST DRAWDOWN',nicePct(worst),'Peak-to-trough loss','metric-negative'],['AVERAGE BETA',niceNum(avgBeta),'Market sensitivity','metric-accent'],['MARKET VOLATILITY',nicePct(r.marketVol),'S&P 500 proxy · annualized','']].map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value ${x[3]}">${x[1]}</div><div class="metric-sub">${x[2]}</div></div>`).join('')}
function renderTable(r){$('asset-table').innerHTML=r.assets.map(a=>{const level=a.vol>.35?'high':a.vol>.22?'med':'low';return`<tr><td>${a.name}</td><td>$${niceNum(a.last)}</td><td>${nicePct(a.vol)}</td><td class="${a.dd<-.2?'metric-negative':''}">${nicePct(a.dd)}</td><td>${niceNum(a.beta)}</td><td><span class="signal signal-${level}">${level==='high'?'Elevated':level==='med'?'Watch':'Stable'}</span></td></tr>`}).join('')}
function drawChart(canvas,series,colors,opts={}){const ctx=canvas.getContext('2d'),rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1,w=Math.max(300,rect.width),h=Math.max(170,rect.height);canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const pad={l:38,r:12,t:12,b:25},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b;const flat=series.flat(),lo=opts.min??Math.min(...flat),hi=opts.max??Math.max(...flat),range=hi-lo||1;ctx.font='10px Inter, sans-serif';ctx.strokeStyle='#e6ece8';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=pad.t+ih*i/3;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillStyle='#9ba6a1';ctx.fillText(opts.format?opts.format(hi-range*i/3):String((hi-range*i/3).toFixed(2)),2,y+3)}series.forEach((line,n)=>{ctx.beginPath();line.forEach((v,i)=>{const x=pad.l+iw*i/(line.length-1),y=pad.t+ih*(hi-v)/range;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=colors[n];ctx.lineWidth=2;ctx.stroke()});ctx.fillStyle='#a4afaa';ctx.fillText('start',pad.l,h-5);ctx.fillText('latest',w-pad.r-28,h-5)}
function renderCharts(r){const priceLines=r.assets.map(a=>a.prices.map(p=>p/a.prices[0]*100));drawChart($('price-chart'),priceLines,['#2d6756','#de754e','#4e86a6'],{min:Math.min(...priceLines.flat())-1,max:Math.max(...priceLines.flat())+1,format:v=>v.toFixed(0)});drawChart($('vol-chart'),[r.marketGarch.map(v=>Math.sqrt(v*CONFIG.TRADING_DAYS)*100)],['#de754e'],{min:0,format:v=>`${v.toFixed(0)}%`});drawChart($('beta-chart'),[r.assets[0].kalman,r.assets[1]?.kalman||r.assets[0].kalman],['#2d6756','#de754e'],{min:Math.min(...r.assets.flatMap(a=>a.kalman))-.1,max:Math.max(...r.assets.flatMap(a=>a.kalman))+.1,format:v=>v.toFixed(1)});$('price-legend').textContent=r.assets.map(a=>a.name).join('  ·  ')}
function render(r){currentReport=r;$('scenario-title').textContent=SCENARIOS[$('asset-select').value]?.title||'Uploaded scenario';$('as-of').textContent=`${r.market.length-1} DAYS`;$('data-source').textContent=r.source;renderMetrics(r);renderTable(r);renderCharts(r)}
function run(){try{$('notice').hidden=true;const scenario=$('asset-select').value,days=Number($('window-select').value),r=analyze(makeSeries(days,scenario,$('market-select').value));render(r)}catch(e){$('notice').textContent=e.message;$('notice').hidden=false}}
function parseCSV(text){const rows=text.trim().split(/\r?\n/).map(x=>x.split(',').map(v=>v.trim()));const head=rows.shift().map(x=>x.toLowerCase());const di=head.indexOf('date'),ai=head.indexOf('asset'),mi=head.indexOf('market');if(ai<0||mi<0)throw Error('CSV needs Asset and Market columns.');const assets=[],market=[];rows.forEach(row=>{const a=Number(row[ai]),m=Number(row[mi]);if(Number.isFinite(a)&&Number.isFinite(m)){assets.push(a);market.push(m)}});if(assets.length<3)throw Error('CSV needs at least three valid rows.');return{market,assets:[{name:'Uploaded asset',prices:assets,noise:0,b:1}],source:`Uploaded CSV${di>=0?' · '+rows.length+' rows':''}`}}
if(typeof document!=='undefined'){$('run-btn').addEventListener('click',run);$('reset-btn').addEventListener('click',()=>{$('asset-select').value='tech';$('window-select').value='120';$('market-select').value='SPY';run()});$('csv-input').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=parseCSV(reader.result);render(analyze(parsed));$('asset-select').value='';}catch(err){$('notice').textContent=err.message;$('notice').hidden=false}};reader.readAsText(file)});$('download-btn').addEventListener('click',()=>{if(!currentReport)return;const rows=[['Asset','Last Price','Annualized Volatility','Max Drawdown','Beta'],...currentReport.assets.map(a=>[a.name,a.last,a.vol,a.dd,a.beta])];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='volarisk-report.csv';a.click();URL.revokeObjectURL(url)});window.addEventListener('resize',()=>currentReport&&renderCharts(currentReport));run()}
export{logReturns,annualizedVolatility,maxDrawdown,beta,garch,kalman};
